# THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT MANUALLY.

from typing import Dict

import sphinx.application

__version__ = ...  # type: str

def get_path() -> str: ...
def setup(app: sphinx.application.Sphinx) -> Dict[str, str]: ...
