# THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT MANUALLY.

from sphinx.directives.patches import RSTTable

import sphinx.application

class ExtendedRSTTable(RSTTable): ...

def setup(app: sphinx.application.Sphinx) -> None: ...
